RedRobinXmlImport/Controllers/ImportXmlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using RedRobin.DataAccess;
using RedRobin.DataAccess.Models;

namespace RedRobinXmlImport.Controllers
{
    public class ImportXmlController : Controller
    {
        //
        // GET: /ImportXml/

        public ActionResult Index()
        {
            return View();
        }



        public ActionResult UploadXml(HttpPostedFileBase SourceFile)
        {
            XmlImportResults result = new XmlImportResults();

            try
            {
                if ( SourceFile == null || SourceFile.ContentLength < 1 || SourceFile.FileName.IsEmpty())
                    throw new ArgumentNullException("SourceFile","No source file selected!");

                result = XmlService.UploadXml(SourceFile.FileName, SourceFile.InputStream);
            }
            catch (Exception e)
            {
                if ( result == null)
                    result = new XmlImportResults();
                result.ErrorMessage = e.Message;
                result.Success = false;
            }

            
            return View("Index", result);
        }

    }
}

RedRobinXmlImport/Controllers/ManageDuplicatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RedRobin.DataAccess;

namespace RedRobinXmlImport.Controllers
{
    public class ManageDuplicatesController : Controller
    {
        //
        // GET: /ManageDuplicates/

        public ActionResult Index()
        {
            var repo = new MatchedItemRepository_pp();
            //var dups = repo.GetXmlIngredientDuplicates();
            var dups = repo.GetDuplicates();
            ViewBag.Total = dups.Duplicates.Count;
            return View(dups);
        }

        //will replace search and replace all matches of itemname in ingredientsxref with itemguid
        public ActionResult ShrinkDuplicates( string itemname, string itemguid,string calories, string quantity)
        {

            var repo = new MatchedItemRepository_pp();
            if (repo.UpdateXrefIngredients(itemname, quantity, calories, itemguid))
                return Content("<div class=\"notify\">All " + itemname + " updated to use " + itemguid + " as matched ingredient</div>");
            else
            {
                return Content("<div class=\"error-message\">Unable to update " + itemname + " to use " + itemguid + ", please refresh and try again.</div>");

            }
        }

    }
}

RedRobinXmlImport/Controllers/MatchedItemsController.cs
using System;
using System.Web.Mvc;
using RedRobin.DataAccess;
using RedRobin.DataAccess.Models;

namespace RedRobinXmlImport.Controllers
{
    public class MatchedItemsController : Controller
    {
        //
        // GET: /MatchedItems/

        public ActionResult MatchedMenuItems()
        {
            var repo = new MatchedItemRepository_pp();
            var model = repo.GetMatchedMenuItems();
            ViewBag.Total = model.Count;
            return View("MatchedMenuItems", model);
        }

        public ActionResult PartialMatchMenuItems()
        {
            var repo = new MatchedItemRepository_pp();
            var model = repo.GetPartialMenuItems();
             ViewBag.Total = model.Count;
            return View("MatchedMenuItems", model);
        }

        public ActionResult UnmatchedMenuItems()
        {
            var repo = new MatchedItemRepository_pp();
            var model = repo.GetUnMatchedMenuItems();
            ViewBag.Total = model.Count;
            return View("MatchedMenuItems", model);
        }

        public ActionResult MatchAggregate(string xmlguid, string menuitemguid)
        {
            var repo = new MatchedItemRepository_pp();
            var aggregate = new XmlMenuItem();

            if ( !string.IsNullOrEmpty(xmlguid))
            {
                aggregate = repo.GetXmlMenuItemWithIngredients(xmlguid);

                foreach (var xmlIngredient in aggregate.Ingredients)
                {
                    //need to get ingredient match, different from menu item ingredients
                    var xref = repo.GetIngredientCrossReference(xmlIngredient.ItemIngredientGuid);
                    if (xref != null && xref.ingredientsguid != null) // means there is no match
                        xmlIngredient.IngredientMatch = repo.GetMatchedIngredient(xref.ingredientsguid.ToString(),true);
//                  
//                    if ( xmlIngredient.IngredientMatch == null)
//                        xmlIngredient.IngredientMatch = new IngredientAggregate();

                }
            }

            if (string.IsNullOrEmpty(menuitemguid))
            {
                //attempt to get from xref
                var xref = repo.GetMenuCrossReference(xmlguid);
                menuitemguid = xref.menuitemguid.ToString();
            }
            if (!string.IsNullOrEmpty(menuitemguid))
                aggregate.MenuItemMatch = repo.GetMenuItemWithIngredients(menuitemguid);


            return View(aggregate);
        }

        public ActionResult GetIngredientDetails(string ingredientId)
        {
            var repo = new MatchedItemRepository_pp();
            var results = repo.GetMatchedIngredient(ingredientId, false);
            return View(results);
        }

        public ActionResult IngredientMatchControl(string xmlingredientid)
        {
            try
            {
                IngredientCandidates candidates = new IngredientCandidates();
                var repo = new MatchedItemRepository_pp();
                var xmlingredient = repo.GetXmlIngredient(xmlingredientid);
                if ( xmlingredient != null )
                    candidates = repo.GetIngredientCandidates(xmlingredient);
                candidates.XmlIngredient = xmlingredient;
                return View (candidates);
            }
            catch (Exception e)
            {
                return Content("<p><div class=\"error-message\">Unable to find candidates, verify the menu item is matched.</div></p>");
            }
        }

        public ActionResult MenuItemMatchControl(string xmlmenuitemid)
        {
            MenuItemCandidates candidates = new MenuItemCandidates();
            var repo = new MatchedItemRepository_pp();
            var xmlmenuitem = repo.GetXmlMenuItem(xmlmenuitemid);
            if (xmlmenuitem != null)
                candidates = repo.GetMenuItemCandidates(xmlmenuitem);
            candidates.XmlMenuItem = xmlmenuitem;
            return View(candidates);
        }

        public ActionResult UpdateIngredientMatch(string xmlguid,string matchedGuid)
        {
            var repo = new MatchedItemRepository_pp();
            var response = "Ingredient Updated to " + matchedGuid;
            try
            {
                if (!repo.UpdateIngredientXref(xmlguid, matchedGuid))
                    response = "Unable to update Ingredient";
            }
            catch (Exception e)
            {
                response = "Oops, an error occured. Details: " + e.Message;
            }

            var ingredient = repo.GetXmlIngredientByGuid(xmlguid);
            ingredient.IngredientMatch = repo.GetMatchedIngredient(matchedGuid, true);

            return PartialView("GetIngredientDetails", ingredient);

            return Content(response);
        }

        public ActionResult UpdateMenuItemsMatch(string xmlguid,string matchedGuid)
        {
            var repo = new MatchedItemRepository_pp();
            repo.UpdateMenuItemsXref(xmlguid, matchedGuid);

            var menuitem = repo.GetXmlMenuItem(xmlguid);
            menuitem.MenuItemMatch = repo.GetMenuItemWithIngredients(matchedGuid);
            return PartialView("GetMenuItemDetails", menuitem);
        }

        public ActionResult UpdateMenuItemMatch(string xmlmenuitem, string matchedguid)
        {
            XmlMenuItem menuitem = new XmlMenuItem();
            return PartialView("GetMenuItemDetails", menuitem);
        }
    }
}

RedRobinXmlImport/Controllers/UpdateNutrionalInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RedRobin.DataAccess;

namespace RedRobinXmlImport.Controllers
{
    public class UpdateNutrionalInformationController : Controller
    {
        //
        // GET: /UpdateNutrionalInformation/
        public ActionResult Index()
        {
            var repo = new MatchedItemRepository_pp();
            
            return View(repo.GetImport());
        }

        public ActionResult UpdateNutritionalInformation()
        {
            var repo = new MatchedItemRepository_pp();
            var results = repo.UpdateMenu();
        
            return View(results);
        }

    }
}

RedRobinXmlImport/Views/Shared/GetIngredientDetails.cshtml
@using RedRobin.DataAccess.Models
@model XmlIngredient
<div class="ingredient-header">

   <div id="match-ingredients-modal">
                        @Html.ActionLink("Click to Select Ingredient Match", "IngredientMatchControl", "MatchedItems",
                        new { xmlingredientid = @Model.XmlImportIngredientId },
                        new { @class = "openDialog", data_dialog_id = "MatchDialog", data_dialog_title = "Find Ingredient for  " + @Model.ItemIngredientName + ", " + @Model.Calories + "Calories" })
                    </div>
</div>
@if (@Model.IngredientMatch != null)
     {
<ul id="ingredient-detail">
    <li>Name: @Model.IngredientMatch.managename</li>
    <li>Id: @Model.IngredientMatch.ingredientid</li>
    <li>Data object id: @Model.IngredientMatch.DataObjectId</li>
    <li>Display name: @Model.IngredientMatch.displayname</li>
    <li>Category: @Model.IngredientMatch.ingredientcategoryid</li>
    @foreach (var nutrient in @Model.IngredientMatch.Nutrients)
{
        if ( !nutrient.NutrientInfo.IsEmpty())
        {
            <li>@nutrient.NutrientInfo</li>
        }
}
</ul>
    }

RedRobinXmlImport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Matchimizer.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
     <script src="@Url.Content("~/Scripts/matchimizer.js")" type="text/javascript"></script>


</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>Customizer Matching</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Upload Xml","Index", "ImportXml")</li>
                    <li>@Html.ActionLink("Update Tool","Index", "UpdateNutrionalInformation")</li>
                    <li>@Html.ActionLink("Matched Items","MatchedMenuItems", "MatchedItems")</li>
                    <li>@Html.ActionLink("Partial Matches", "PartialMatchMenuItems", "MatchedItems")</li>
                    <li>@Html.ActionLink("Un-matched Items","UnmatchedMenuItems", "MatchedItems")</li>
                    <li>@Html.ActionLink("Manage Duplicates","Index", "ManageDuplicates")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

RedRobinXmlImport/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}